name: TempRanks
main: ErosionYT\TempRanks\Main
version: 2.0.0
api: 4.0.0
load: POSTWORLD
author: ErosionYT
description: Give temporary ranks to players
depend: [PurePerms]

commands:
 temprank:
  description: "Manage temporary ranks"
  usage: "/temprank set/remove"
  permission: temprank.command

permissions:
  temprank.command:
   default: op
   description: "Allows the use of /temprank"