--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ErosionYT/tempranks-pmp
build-by-default: true
branches:
- main
projects:
  tempranks-pmp:
    path: ""
libs:
  - src: "_64FF00\PurePerms\PurePerms"
    version: "1.4.1-5"
...
